/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities/index'
import { Route as OpportunitiesOpportunityIdRouteImport } from './routes/opportunities/$opportunityId'
import { Route as ApiOpportunitiesIndexRouteImport } from './routes/api/opportunities/index'
import { Route as ApiOpportunitiesOpportunityIdRouteImport } from './routes/api/opportunities/$opportunityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOpportunityIdRoute =
  OpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpportunitiesIndexRoute = ApiOpportunitiesIndexRouteImport.update({
  id: '/api/opportunities/',
  path: '/api/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpportunitiesOpportunityIdRoute =
  ApiOpportunitiesOpportunityIdRouteImport.update({
    id: '/api/opportunities/$opportunityId',
    path: '/api/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/opportunities/$opportunityId': typeof ApiOpportunitiesOpportunityIdRoute
  '/api/opportunities/': typeof ApiOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/api/opportunities/$opportunityId': typeof ApiOpportunitiesOpportunityIdRoute
  '/api/opportunities': typeof ApiOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/opportunities/$opportunityId': typeof ApiOpportunitiesOpportunityIdRoute
  '/api/opportunities/': typeof ApiOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/opportunities/$opportunityId'
    | '/opportunities/'
    | '/api/opportunities/$opportunityId'
    | '/api/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/opportunities/$opportunityId'
    | '/opportunities'
    | '/api/opportunities/$opportunityId'
    | '/api/opportunities'
  id:
    | '__root__'
    | '/'
    | '/opportunities/$opportunityId'
    | '/opportunities/'
    | '/api/opportunities/$opportunityId'
    | '/api/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpportunitiesOpportunityIdRoute: typeof OpportunitiesOpportunityIdRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ApiOpportunitiesOpportunityIdRoute: typeof ApiOpportunitiesOpportunityIdRoute
  ApiOpportunitiesIndexRoute: typeof ApiOpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$opportunityId': {
      id: '/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof OpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opportunities/': {
      id: '/api/opportunities/'
      path: '/api/opportunities'
      fullPath: '/api/opportunities/'
      preLoaderRoute: typeof ApiOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opportunities/$opportunityId': {
      id: '/api/opportunities/$opportunityId'
      path: '/api/opportunities/$opportunityId'
      fullPath: '/api/opportunities/$opportunityId'
      preLoaderRoute: typeof ApiOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpportunitiesOpportunityIdRoute: OpportunitiesOpportunityIdRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ApiOpportunitiesOpportunityIdRoute: ApiOpportunitiesOpportunityIdRoute,
  ApiOpportunitiesIndexRoute: ApiOpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
